### ISSUE TITLE
Sever crash with Null reference exception when trying to create a logger

### ISSUE THREAD

**Issue by omerlh** [damianh/LibLog#172]
Hey
I'm using AppMetrics, which use LibLog. After using it for a while, yesterday I bumped into a weird issue - when trying to run my code on docker it crash with a weird error (see AppMetrics/AppMetrics#289):
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'App.Metrics.Internal.DefaultMetricContextRegistry' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: method
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at System.Runtime.CompilerServices.CallSite`1.CreateCustomNoMatchDelegate(MethodInfo invoke)
   at System.Runtime.CompilerServices.CallSite`1.MakeUpdateDelegate()
   at System.Runtime.CompilerServices.CallSite`1.GetUpdateDelegate(T& addr)
   at System.Runtime.CompilerServices.CallSite`1.Create(CallSiteBinder binder)
   at App.Metrics.Logging.LogProvider.get_CurrentLogProvider()
   at App.Metrics.Logging.LogProvider.GetLogger(String name)
   at App.Metrics.Internal.DefaultMetricContextRegistry..cctor()
   --- End of inner exception stack trace ---
   at App.Metrics.Internal.DefaultMetricContextRegistry.<>c__DisplayClass16_0`1.<Apdex>b__0()
   at App.Metrics.Internal.DefaultMetricContextRegistry.MetricMetaCatalog`3.<>c__DisplayClass4_0.<GetOrAdd>b__0(String n)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at App.Metrics.Internal.DefaultMetricContextRegistry.MetricMetaCatalog`3.GetOrAdd(String name, Func`1 metricProvider)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware..ctor(RequestDelegate next, IOptions`1 trackingMiddlwareOptionsAccessor, ILogger`1 logger, IMetrics metrics)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.UseWhenExtensions.<>c__DisplayClass0_0.<UseWhen>b__0(RequestDelegate main)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at <>.Program.Main(String[] args)
```
I'm still digging, but wasn't able to find the root cause of this bug. The logging framework I'm using is Serilog, which seems that is not detected. I'm trying to read the code - look like the exception is thrown from [this method](https://github.com/AppMetrics/AppMetrics/blob/af4bc5883f0e3cbf1d6f43024b5843e70899186f/src/App.Metrics.Core/App_Packages/LibLog.g.cs#L609), but I can't figure out why this code will throw.
Could you help me out?

**Comment by damianh** [comment]
Any repro code you can share with me please? Would like to investigate this.

**Comment by omerlh** [comment]
I think the issue is related to `microsoft/dotnet:2.0-runtime-deps`, which was published 3 days ago. Once I've rolled back to a previous version, things started to work.
I'll try to create a sample repo, hope it will reproduce.

**Comment by omerlh** [comment]
Ok, tried to reproduce on clean repo - but couldn't. I will close the issue for now...
