### ISSUE TITLE
FormatExceptions when updgrading to 3.1

### ISSUE THREAD

**Issue by leastprivilege** [damianh/LibLog#53]
see here

https://ci.appveyor.com/project/leastprivilege/thinktecture/build/2.0.5

kthxbye ;)

**Comment by damianh** [comment]
```
IdentityServer3.Tests.Validation.TokenRequest.TokenRequestValidation_Valid.Valid_ResourceOwner_Request [FAIL]
      System.FormatException : The input string '{\r\n  "Category": "Authentication",\r\n  "Name": "Resource Owner Password Flow Login Success",\r\n  "EventType": "Success",\r\n  "Id": 1050,\r\n  "Details": {\r\n    "LoginUserName": "bob",\r\n    "SignInMessage": {\r\n      "ClientId": "roclient",\r\n      "AcrValues": [],\r\n      "Created": 635632296692409355\r\n    },\r\n    "PartialLogin": false,\r\n    "SubjectId": "bob"\r\n  }\r\n}' could not be formatted using string.Format\r\n---- System.FormatException : Input string was not in a correct format.
      Stack Trace:
         source\Core\App_Packages\LibLog.3.1\LibLog.cs(1840,0): at IdentityServer3.Core.Logging.LogProviders.LogMessageFormatter.<>c__DisplayClass1.<SimulateStructuredLogging>b__0()
         source\Core\App_Packages\LibLog.3.1\LibLog.cs(1747,0): at IdentityServer3.Core.Logging.LogProviders.ColouredConsoleLogProvider.ColouredConsoleLogger.Log(LogLevel logLevel, Func`1 messageFunc, Exception exception, Object[] formatParameters)
         source\Core\App_Packages\LibLog.3.1\LibLog.cs(506,0): at IdentityServer3.Core.Logging.LoggerExecutionWrapper.Log(LogLevel logLevel, Func`1 messageFunc, Exception exception, Object[] formatParameters)
         source\Core\App_Packages\LibLog.3.1\LibLog.cs(208,0): at IdentityServer3.Core.Logging.LogExtensions.Info(ILog logger, String message)
         source\Core\Services\Default\DefaultEventService.cs(44,0): at IdentityServer3.Core.Services.Default.DefaultEventService.RaiseAsync[T](Event`1 evt)
         source\Core\Extensions\IEventServiceExtensions.cs(570,0): at IdentityServer3.Core.Extensions.IEventServiceExtensions.<RaiseEventAsync>d__9f`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         source\Core\Extensions\IEventServiceExtensions.cs(174,0): at IdentityServer3.
```

**Comment by leastprivilege** [comment]
yep

**Comment by damianh** [comment]
Just copying the exception incase AppVeyor builds get cleaned up.

**Comment by damianh** [comment]
Ping @Erwinvandervalk looks like this problem is coming from the `SimulateStructuredLogging`, can you take a look? It appears that IdSrv3 is logging json strings and it's causing this to blow.

**Comment by Erwinvandervalk** [comment]
This is the same issue as #34. It was fixed in the latest release. 
![image](https://cloud.githubusercontent.com/assets/6771385/6979905/7ac5a0ba-d9ea-11e4-9f0e-06f7f9b0bf62.png)

**Comment by Erwinvandervalk** [comment]
@leastprivilege would you mind giving release 4.0.2 a spin? that should solve this issue

**Comment by leastprivilege** [comment]
Yep - you are right. thanks!

Now I only need a way to disable console output in appveyor builds.

**Comment by leastprivilege** [comment]
Still like the env variable idea. nice and simple. Shuts down logging altogether.

**Comment by damianh** [comment]
@leastprivilege See Q on https://github.com/damianh/LibLog/pull/57

**Comment by damianh** [comment]
Thx @Erwinvandervalk :)

**Comment by adamralph** [comment]
This should be milestone 4.0.1

**Comment by adamralph** [comment]
That concludes my milestone policing :stuck_out_tongue: 

4.0.2 doesn't have anything associated with it, but the only fix was https://github.com/damianh/LibLog/commit/de52ae032b595f2a94853ac634e5fc27cb455e44 which went straight onto master so no PR to link, and no issue was raised (apart from a tweet :wink:).

**Comment by damianh** [comment]
I should just hand this project over to you :wink:

**Comment by adamralph** [comment]
*winds self back in* :blush:
